[package]
name = "rust_ogl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brood = { version = "0.9.1", features = ["rayon"] }
glam = "0.27.0"
glium = "0.34.0"
jumprope = "1.1.2"
winit = "0.29.15"
